### ISSUE TITLE
Do not see Token Compendium

### ISSUE THREAD

**Issue by Shareenx** [Caeora/Caeora-s-Maps-Tokens-Assets#8]
I installed Foundry VTT and Caeora's Assets on a machine last week- I saw the wonderful maps and tokens (I was seeing which modules I liked). I then installed them on my gaming machine, and Caeora's Assetsd yesterday. 
Mid install, we lost power and internet, and when it came back, it looked like it had not installed, so I installed the module again via the Foundry VTT interface. When I launched the world and navigated to the Compendiums, the only one I could find was the maps.

I uninstalled, searched the VTT directory for "caeora", searched the registry for the same. Nothing. Closed and opened the VTT again and tried reinstalling. Same issue. When I open the file directory, I can see the token and asset images, but I do not see them in the VTT UI.

I am not sure if it was the power outtage or something else.

I've attached some screenshots to try and explain what I am seeing.

VTT version 0.7.9
Caeora's- today 3/21
![OneTokenDirecroty](https://user-images.githubusercontent.com/81126418/111930733-d472cf00-8a76-11eb-95ed-59f65eab6ebe.PNG)
![AssetRoot](https://user-images.githubusercontent.com/81126418/111930748-dc327380-8a76-11eb-9b7e-606c0bceaa4f.PNG)
![Module Settings](https://user-images.githubusercontent.com/81126418/111930630-9aa1c880-8a76-11eb-93ca-9f7977d7fcbb.PNG)
![version](https://user-images.githubusercontent.com/81126418/111930632-9aa1c880-8a76-11eb-8658-f1738a66d53c.PNG)
![Actor](https://user-images.githubusercontent.com/81126418/111930625-99709b80-8a76-11eb-9bc6-0bb43e1eaf00.PNG)
![Compendium Packs](https://user-images.githubusercontent.com/81126418/111930628-9a093200-8a76-11eb-8c35-e216f2d5dd5c.PNG)

**Comment by Malekal4699** [comment]
Hi, there is no compendium with the images.

Try importing a black bear from the SRD compendium, then drag it to the scene. The token should be the bear.

**Comment by Shareenx** [comment]
I, apparently, was completely mistaken and dreamt the whole thing.
Glitch in the matrix, because I was sure I saw the tokens in the VTT, but
checking the other machine this morning. No. No I did not. I apologize.
